source "https://rubygems.org"

gem "rails", "~> 8.1.2"

gem "pg", "~> 1.1"

gem "puma", ">= 5.0"

gem "jbuilder"

gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "bootsnap", require: false

gem "thruster", require: false

gem "image_processing", "~> 1.2"

gem "rack-cors"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  gem "bundler-audit", require: false

  gem "brakeman", require: false

  gem "rubocop-rails-omakase", require: false
end

gem "dotenv", "~> 3.2", groups: [:development, :test]

gem "rspec-rails", "~> 8.0", groups: [:development, :test]

gem "spring-commands-rspec", "~> 1.0", group: :development

gem "factory_bot_rails", "~> 6.5", groups: [:development, :test]

gem "shoulda-matchers", "~> 7.0", group: :test
